version: 0.2

phases:
  pre_build:
    commands:
      - echo MN Starting install Horusec `date` . . .
      - echo MN Possible unknown vulnerabilities will be found by analyzing
      - VERSION="v2.9.0-beta.3"
      - curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/$VERSION/deployments/scripts/install.sh | bash -s latest-beta  

  build:
    commands:
      - echo MN Build started on `date`
      - docker -v
      - echo MN Scanning with horusec...
      - horusec start -p="./" -o="json" -O="./vul-horusec.json" || EXIT_CODE=$?

  post_build:
    commands:
      - echo MN Build completed on `date`
      - wget --quiet https://roxsross-linktree.s3.amazonaws.com/horusec_vulnerability.py
      - python horusec_vulnerability.py vul-horusec.json
artifacts:
  files: vul-horusec.json
