# Contexto: AWS CodeBuild
# Fases y comandos que se ejecutan durante el proces de compilación
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Checking for build type
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker build -t $REPO_URL $FOLDER_PATH
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URL:$IMAGE_TAG
      - echo Create folder infra-templates
      - mkdir -p ./build-templates
      - echo Changing directory to Templates directory
      - cd ./build-templates
      - echo Copy of S3 templates Scripts
      - aws s3 cp s3://mn-infra/templates/horusec_vulnerability.py .
      - aws s3 cp s3://mn-infra/templates/trivy_vulnerability.py .
      - echo Preparing spec files in new folder
      - mkdir artifacts
      - echo Changing directory to the Artifacts directory
      - cd artifacts
      - echo Copy taskdef and appspect to artifacts
      - aws s3 cp s3://mn-infra/templates/taskdef.json .
      - aws s3 cp s3://mn-infra/templates/appspec.yaml .
      - ls -lrt
      - echo Preparating artifacts
      - sed -i "s|<TASK_DEFINITION_FAMILY>|$TASK_DEFINITION_FAMILY|g" taskdef.json
      - sed -i "s|<CONTAINER_NAME>|$CONTAINER_NAME|g" appspec.yaml taskdef.json
      - sed -i "s|<SERVICE_PORT>|$SERVICE_PORT|g" appspec.yaml taskdef.json
      - sed -i "s|<ECS_ROLE>|$ECS_ROLE|g" taskdef.json
      - sed -i "s|<ECS_TASK_ROLE>|$ECS_TASK_ROLE|g" taskdef.json
      - sed -i "s|<REPO_URL>|$REPO_URL|g" taskdef.json
      - sed -i "s|<AWS_ACCOUNT_ID>|$AWS_ACCOUNT_ID|g" taskdef.json
      - sed -i "s|<AWS_REGION>|$AWS_REGION|g" taskdef.json

artifacts:
  files:
    - '**/*'
  base-directory: 'build-templates/artifacts'
  discard-paths: yes
